language: perl
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
install:
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls
#    - cpanm --quiet --installdeps .
script: 
    - perl Makefile.PL
    - make
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrv
    - cover
after_success:
    - cover -report coveralls
